name: SASjs Server Executable Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies WEB
        working-directory: ./web
        run: npm ci

      - name: Build WEB
        working-directory: ./web
        run: npm run build
        env:
          CI: true

      - name: Install Dependencies API
        working-directory: ./api
        run: npm ci

      - name: Build Executables
        working-directory: ./api
        run: npm run exe
        env:
          CI: true

      - name: Compress Executables
        working-directory: ./executables
        run: |
          zip linux.zip api-linux
          zip macos.zip api-macos
          zip windows.zip api-win.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./executables/linux.zip
            ./executables/macos.zip
            ./executables/windows.zip
